// Generate a numbered baseball data migration from the capture cache + registry.
// Run: node scripts/baseball/generate-migration.mts [--out-dir supabase/migrations]
//
// Reads every scripts/baseball/.cache/*.json plus people.json, picks the next
// migration number, and writes NNNNN_baseball_data_<slug>.sql. Aborts (exit 1)
// if any captured roster player is still unresolved in people.json — confirm
// identities first (see docs/baseball-import-runbook.md). Pure SQL generation
// lives in sql.ts; this file is just the I/O wrapper.

import { readFileSync, readdirSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { buildMigrationSql, type Cache } from "./sql.ts";
import type { Registry } from "./identity.ts";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..", "..");
const cacheDir = join(here, ".cache");
const migrationsDir = join(repoRoot, "supabase", "migrations");

function loadRegistry(): Registry {
  const raw = JSON.parse(readFileSync(join(here, "people.json"), "utf8"));
  return { people: raw.people, aliases: raw.aliases };
}

function loadCaches(): Cache[] {
  if (!existsSync(cacheDir)) return [];
  return readdirSync(cacheDir)
    .filter((f) => f.endsWith(".json"))
    .map((f) => JSON.parse(readFileSync(join(cacheDir, f), "utf8")) as Cache);
}

// Next number = max of committed migration files + 1, zero-padded to 5.
// (Shared-DB collisions across workspaces still warrant a glance at
// supabase_migrations.schema_migrations before merge — see the runbook.)
function nextMigrationNumber(): string {
  const nums = readdirSync(migrationsDir)
    .map((f) => f.match(/^(\d{5})_/)?.[1])
    .filter((x): x is string => !!x)
    .map((x) => parseInt(x, 10));
  const next = (nums.length ? Math.max(...nums) : 0) + 1;
  return String(next).padStart(5, "0");
}

function main() {
  const caches = loadCaches();
  if (!caches.length) {
    console.error(`No captures found in ${cacheDir}. Run \`npm run baseball:capture\` first.`);
    process.exit(1);
  }
  const registry = loadRegistry();
  let sql: string;
  try {
    sql = buildMigrationSql(caches, registry);
  } catch (e) {
    console.error(`\n${(e as Error).message}\n`);
    process.exit(1);
  }
  const number = nextMigrationNumber();
  const slug = caches.length === 1 ? slugifyTeam(caches[0].team.name) : "batch";
  const filename = `${number}_baseball_data_${slug}.sql`;
  const dest = join(migrationsDir, filename);
  const header = `-- ${filename}\n-- Generated by scripts/baseball/generate-migration.mts from ${caches.length} capture(s).\n\n`;
  writeFileSync(dest, header + sql);
  console.log(`Wrote supabase/migrations/${filename} (${caches.length} team-season(s)).`);
  console.log("Review the diff, then merge to apply on deploy.");
}

function slugifyTeam(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, "").slice(0, 40);
}

main();
