-- Per-user preferred substitutes: "I can't do pistols → suggest goblet squats".
-- Personal (not global), so it's a per-user table with own-rows RLS. One preferred
-- substitute per movement; the substitute itself is a movement in the shared
-- library (picked via typeahead or generated by AI and added to the library).
CREATE TABLE workout_movement_substitutions (
  id                     uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id                uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  movement_id            uuid NOT NULL REFERENCES movements(id) ON DELETE CASCADE,
  substitute_movement_id uuid NOT NULL REFERENCES movements(id) ON DELETE CASCADE,
  created_at             timestamptz NOT NULL DEFAULT now(),
  updated_at             timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, movement_id),
  CONSTRAINT chk_substitute_differs CHECK (movement_id <> substitute_movement_id)
);

CREATE INDEX idx_workout_subs_user ON workout_movement_substitutions (user_id);

CREATE TRIGGER workout_substitutions_updated_at
  BEFORE UPDATE ON workout_movement_substitutions
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

ALTER TABLE workout_movement_substitutions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Own rows" ON workout_movement_substitutions FOR ALL
  USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
